server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.project: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate: 
        "[format_sql]": true

        
        # docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=123 -v C:\volumn\postgres:/var/lib/postgresql/data postgres:latest
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
#    username: cos
#    password: cos1234
    
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
